name = "dofusdle"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SOLVE_COUNTS"
id = "b124dcd877b743139b0cf12728493a60"
preview_id = "b0b31ffba87e40a2a7355d5bfea54849"
